# Generated by Django 2.1.5 on 2019-01-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='date_mise_sous_essai',
        ),
    ]
