# Generated by Django 2.1.7 on 2019-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyse',
            old_name='var1_silicate',
            new_name='var1_sil_650',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='var1_silice_ifremer',
            new_name='var1_sil_815',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='var1_silice',
            new_name='var1_sil_bc',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='var2_silicate',
            new_name='var2_sil_650',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='var2_silice_ifremer',
            new_name='var2_sil_815',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='var2_silice',
            new_name='var2_sil_bc',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='var3_silicate',
            new_name='var3_sil_650',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='var3_silice',
            new_name='var3_sil_bc',
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='var3_silice_ifremer',
        ),
        migrations.AddField(
            model_name='analyse',
            name='var3_sil_815',
            field=models.CharField(default='null', max_length=60, verbose_name='concentration en mg/L SiO2'),
        ),
    ]
