# Generated by Django 2.1.7 on 2019-05-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190529_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='var3_sil_815',
            field=models.CharField(max_length=60, verbose_name='concentration en SiO2 µg/L'),
        ),
    ]
