# Generated by Django 2.1.7 on 2019-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190529_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='etalonnage',
            name='c_micro_gl',
            field=models.CharField(default='null', max_length=100, verbose_name='concentration en µg/L'),
        ),
    ]
