# Generated by Django 2.1.5 on 2019-01-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_feuille_calcul_date_mise_sous_essai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='date_mise_sous_essai',
        ),
    ]
