# Generated by Django 2.1.7 on 2019-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_feuille_calcul_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_dbo_sans_dilution',
            field=models.DateField(blank=True, verbose_name='Date de préparation de la solution de lavage'),
        ),
    ]
