# Generated by Django 2.1.5 on 2019-01-31 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_feuille_calcul_date_mise_sous_essai'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuille_calcul',
            name='date_mise_sous_essai',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 15, 58, 41, 854512)),
        ),
    ]
