# Generated by Django 2.1.7 on 2019-06-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_etalonnage_c_micro_gl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='var17_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name="'"),
        ),
    ]
