# Generated by Django 2.1.5 on 2019-01-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_feuille_calcul_date_mise_sous_essai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuille_calcul',
            name='date_mise_sous_essai',
            field=models.CharField(max_length=60),
        ),
    ]
