# Generated by Django 2.1.5 on 2019-02-04 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190204_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuille_calcul',
            name='heure_mise_sous_essai',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='date_analyse',
            field=models.DateField(default=datetime.datetime(2019, 2, 4, 22, 45, 44, 321506)),
        ),
    ]
