# Generated by Django 2.1.5 on 2019-02-04 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190204_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuille_calcul',
            name='date_analyse',
            field=models.DateField(default=datetime.datetime(2019, 2, 4, 22, 53, 42, 250084)),
        ),
    ]
