# Generated by Django 2.1.5 on 2019-02-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190204_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuille_calcul',
            name='date_analyse',
            field=models.DateField(),
        ),
    ]
