# Generated by Django 2.1.5 on 2019-02-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190205_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='nEchantillon',
            field=models.CharField(max_length=60, verbose_name="numero d'echantillon"),
        ),
    ]
