# Generated by Django 2.1.5 on 2019-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20190206_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre_interne_analyse',
            name='valeur',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
