# Generated by Django 2.1.5 on 2019-02-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20190206_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_mest',
            field=models.CharField(default='NULL', max_length=60, verbose_name='numéro de lot des filtres'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var2_mest',
            field=models.CharField(default='NULL', max_length=60, verbose_name='MEST de la solution de cellulose microcristalline(mg/L)'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var3_mest',
            field=models.CharField(default='NULL', max_length=60, verbose_name='rendement(%)'),
        ),
        migrations.AddField(
            model_name='parametre_externe_analyse',
            name='valeur',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
