# Generated by Django 2.1.5 on 2019-02-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_feuille_calcul_var4_mest'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_ntk',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Date de préparation du mélange catalyseur'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var2_ntk',
            field=models.CharField(default='NULL', max_length=100, verbose_name='N° de lot H2SO4'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var3_ntk',
            field=models.CharField(default='NULL', max_length=100, verbose_name='N° de lot acide chlorhydrique'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var4_ntk',
            field=models.CharField(default='NULL', max_length=100, verbose_name='N° de lot de l’acide borique'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var5_ntk',
            field=models.CharField(default='NULL', max_length=100, verbose_name='visa'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_mest',
            field=models.CharField(default='NULL', max_length=100, verbose_name='numéro de lot des filtres'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var2_mest',
            field=models.CharField(default='NULL', max_length=100, verbose_name='MEST de la solution de cellulose microcristalline(mg/L)'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var3_mest',
            field=models.CharField(default='NULL', max_length=100, verbose_name='rendement(%)'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var4_mest',
            field=models.CharField(default='NULL', max_length=100, verbose_name='date de préparation de la solution de cellulose microcristalline'),
        ),
    ]
