# Generated by Django 2.1.5 on 2019-02-07 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20190207_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuille_calcul',
            name='date_etalonnage',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'étalonnage"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='longueur_onde',
            field=models.CharField(default='NULL', max_length=100, verbose_name="longueur d'onde d'analyse"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='visa',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Visa'),
        ),
    ]
