# Generated by Django 2.1.5 on 2019-02-07 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20190207_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_dbo_avec_dilution',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="date de préparation de l'eau de dilution"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_dbo_sans_dilution',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de préparation de la solution de lavage'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var2_dbo_avec_dilution',
            field=models.CharField(default='NULL', max_length=100, verbose_name="N° échant utilisé pour l'eau de dilution ensemencée"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var3_dbo_avec_dilution',
            field=models.CharField(default='NULL', max_length=100, verbose_name='DCO de cette échantillon'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var3_ntk',
            field=models.CharField(default='NULL', max_length=100, verbose_name='N° de lot acide chlorhydrique'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var4_ntk',
            field=models.CharField(default='NULL', max_length=100, verbose_name='N° de lot de l’acide borique'),
        ),
    ]
