# Generated by Django 2.1.5 on 2019-02-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_auto_20190218_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etalonnage',
            name='absorbance',
            field=models.CharField(max_length=100, verbose_name='absorbance'),
        ),
        migrations.AlterField(
            model_name='etalonnage',
            name='c_lauryl',
            field=models.CharField(max_length=100, verbose_name='concentration mg/L de lauryl sulfate de sodium'),
        ),
        migrations.AlterField(
            model_name='etalonnage',
            name='c_mg',
            field=models.CharField(max_length=100, verbose_name='concentration mg/L'),
        ),
        migrations.AlterField(
            model_name='etalonnage',
            name='c_micromol_l',
            field=models.CharField(max_length=100, verbose_name='concentration µmol/L'),
        ),
    ]
