# Generated by Django 2.1.5 on 2019-03-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_auto_20190221_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_analyse',
            name='parametre_externe',
            field=models.ManyToManyField(blank=True, to='myapp.Parametre_externe_analyse'),
        ),
        migrations.AlterField(
            model_name='type_analyse',
            name='parametre_interne',
            field=models.ManyToManyField(blank=True, to='myapp.Parametre_interne_analyse'),
        ),
    ]
