# Generated by Django 2.1.7 on 2019-03-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_remove_feuille_paillasse_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuille_calcul',
            name='date_etalonnage',
            field=models.DateField(verbose_name="Date de l'étalonnage"),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='longueur_onde',
            field=models.CharField(max_length=100, verbose_name="longueur d'onde d'analyse"),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var10_dco',
            field=models.CharField(max_length=100, verbose_name='Blanc'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_chlorophylle_lorenzen',
            field=models.CharField(max_length=100, verbose_name="Lot d'acide chlorydrique utilisé"),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_chlorophylle_scor_unesco',
            field=models.CharField(max_length=100, verbose_name="Lot d'acétone utilisé"),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_dbo_avec_dilution',
            field=models.DateField(verbose_name="date de préparation de l'eau de dilution"),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_dbo_sans_dilution',
            field=models.DateField(verbose_name='Date de préparation de la solution de lavage'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_dco',
            field=models.DateField(verbose_name='date de minéralisation'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_mest',
            field=models.CharField(max_length=100, verbose_name='numéro de lot des filtres'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_ntk',
            field=models.DateField(verbose_name='Date de préparation du mélange catalyseur'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_oxygene_dissous',
            field=models.CharField(max_length=100, verbose_name="Volume thiosulfate versé pour l'étalonnage mL"),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var2_chlorophylle_lorenzen',
            field=models.CharField(max_length=100, verbose_name="Lot d'acétone utilisé"),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var2_dbo_avec_dilution',
            field=models.CharField(max_length=100, verbose_name="N° échant utilisé pour l'eau de dilution ensemencée"),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var2_dco',
            field=models.DateField(verbose_name='date de titration'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var2_mest',
            field=models.CharField(max_length=100, verbose_name='MEST de la solution de cellulose microcristalline(mg/L)'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var2_ntk',
            field=models.CharField(max_length=100, verbose_name='N° de lot H2SO4'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var2_oxygene_dissous',
            field=models.CharField(max_length=100, verbose_name='Concentration du thiosulfate de sodium mmol/L'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var3_chlorophylle_lorenzen',
            field=models.DateField(verbose_name="Date de préparation de l'HCI"),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var3_dbo_avec_dilution',
            field=models.CharField(max_length=100, verbose_name='DCO de cette échantillon'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var3_dco',
            field=models.CharField(max_length=100, verbose_name='Lot de la solution ferroïne'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var3_ntk',
            field=models.CharField(max_length=100, verbose_name='N° de lot acide chlorhydrique'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var4_dco',
            field=models.CharField(max_length=100, verbose_name='Lot du H2SO4 4 mol/l'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var4_mest',
            field=models.DateField(verbose_name='date de préparation de la solution de cellulose microcristalline'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var4_ntk',
            field=models.CharField(max_length=100, verbose_name='N° de lot de l’acide borique'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var5_dco',
            field=models.CharField(max_length=100, verbose_name='volume de sulfate versé pour la détermintation de sa concentration'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var6_dco',
            field=models.CharField(max_length=100, verbose_name='valeur de solution de référence C'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var8_dco',
            field=models.CharField(max_length=100, verbose_name='lot de sulfate de mercure'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var9_dco',
            field=models.CharField(max_length=100, verbose_name="lot de sulfate d'argent"),
        ),
        migrations.AlterField(
            model_name='parametre_externe_analyse',
            name='valeur',
            field=models.CharField(max_length=100),
        ),
    ]
