# Generated by Django 2.1.7 on 2019-03-25 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_auto_20190325_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuille_calcul',
            name='date_etalonnage',
            field=models.DateField(default=datetime.datetime(1980, 1, 1, 1, 1, 1), verbose_name="Date de l'étalonnage"),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='etalonnage',
            field=models.CharField(max_length=100, verbose_name='Etalonnage'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_dbo_avec_dilution',
            field=models.DateField(default=datetime.datetime(1980, 1, 1, 1, 1, 1), verbose_name="date de préparation de l'eau de dilution"),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_dbo_sans_dilution',
            field=models.DateField(default=datetime.datetime(1980, 1, 1, 1, 1, 1), verbose_name='Date de préparation de la solution de lavage'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_dco',
            field=models.DateField(default=datetime.datetime(1980, 1, 1, 1, 1, 1), verbose_name='date de minéralisation'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_ntk',
            field=models.DateField(default=datetime.datetime(1980, 1, 1, 1, 1, 1), verbose_name='Date de préparation du mélange catalyseur'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var2_dco',
            field=models.DateField(default=datetime.datetime(1980, 1, 1, 1, 1, 1), verbose_name='date de titration'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var3_chlorophylle_lorenzen',
            field=models.DateField(default=datetime.datetime(1980, 1, 1, 1, 1, 1), verbose_name="Date de préparation de l'HCI"),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var3_mest',
            field=models.CharField(max_length=100, verbose_name='rendement(%)'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var4_mest',
            field=models.DateField(default=datetime.datetime(1980, 1, 1, 1, 1, 1), verbose_name='date de préparation de la solution de cellulose microcristalline'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var5_dco',
            field=models.CharField(default='NULL', max_length=100, verbose_name='volume de sulfate versé pour la détermintation de sa concentration'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var6_dco',
            field=models.CharField(default='NULL', max_length=100, verbose_name='valeur de solution de référence C'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var7_dco',
            field=models.CharField(max_length=100, verbose_name='essaie à blanc V1'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='visa',
            field=models.CharField(max_length=100, verbose_name='Visa'),
        ),
    ]
