# Generated by Django 2.1.7 on 2019-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_auto_20190325_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var5_dco',
            field=models.CharField(max_length=100, verbose_name='volume de sulfate versé pour la détermintation de sa concentration'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var6_dco',
            field=models.CharField(max_length=100, verbose_name='valeur de solution de référence C'),
        ),
    ]
