# Generated by Django 2.1.7 on 2019-04-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_auto_20190404_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='var1_kmno4',
            field=models.CharField(max_length=60, verbose_name='V0 (mL)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_kmno4',
            field=models.CharField(max_length=60, verbose_name='V1 (mL)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_kmno4',
            field=models.CharField(max_length=60, verbose_name='V2 (mL)'),
        ),
    ]
