# Generated by Django 2.1.7 on 2019-05-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_auto_20190408_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre_interne_analyse',
            name='rang',
            field=models.IntegerField(default=2),
        ),
    ]
