# Generated by Django 2.1.7 on 2019-05-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_parametre_interne_analyse_rang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre_interne_analyse',
            name='rang',
            field=models.IntegerField(),
        ),
    ]
