# Generated by Django 2.1.5 on 2019-01-22 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nEchantillon', models.CharField(max_length=60)),
                ('m1', models.CharField(default='NULL', max_length=60)),
                ('m2', models.CharField(default='NULL', max_length=60)),
                ('ma', models.CharField(default='NULL', max_length=60)),
                ('mb', models.CharField(default='NULL', max_length=60)),
                ('mc', models.CharField(default='NULL', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Echantillon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Feuille_calcul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feuille_paillasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Parametre_externe_analyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Parametre_interne_analyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Type_analyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('parametre_externe', models.ManyToManyField(to='myapp.Parametre_externe_analyse')),
                ('parametre_interne', models.ManyToManyField(to='myapp.Parametre_interne_analyse')),
            ],
        ),
        migrations.AddField(
            model_name='feuille_paillasse',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Profil'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='feuille_paillasse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Feuille_paillasse'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='type_analyse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Type_analyse'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='echantillon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Echantillon'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='feuille_calcul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Feuille_calcul'),
        ),
    ]
