# Generated by Django 2.1.5 on 2019-01-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='m1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='m2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='ma',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='mb',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='mc',
            field=models.CharField(max_length=60),
        ),
    ]
