# Generated by Django 2.1.5 on 2019-01-31 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_feuille_calcul_date_mise_sous_essai'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuille_calcul',
            name='date_mise_sous_essai',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 11, 17, 41, 727013)),
        ),
    ]
