# Generated by Django 2.1.5 on 2019-01-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190123_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='resultat',
            field=models.CharField(default='NULL', max_length=60),
        ),
    ]
