# Generated by Django 2.1.5 on 2019-01-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_analyse_resultat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='resultat',
            field=models.CharField(max_length=60),
        ),
    ]
