# Generated by Django 2.1.5 on 2019-02-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190206_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyse',
            name='facteur_dilution',
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='resultat_mg_l',
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='v0',
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='v1',
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='v2',
        ),
        migrations.AddField(
            model_name='analyse',
            name='var1_kmno4',
            field=models.CharField(default='NULL', max_length=60, verbose_name='V0'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='var2_kmno4',
            field=models.CharField(default='NULL', max_length=60, verbose_name='V1'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='var3_kmno4',
            field=models.CharField(default='NULL', max_length=60, verbose_name='V2'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='var4_kmno4',
            field=models.CharField(default='NULL', max_length=60, verbose_name='Facteur dilution'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='var5_kmno4',
            field=models.CharField(default='NULL', max_length=60, verbose_name='Resultat en mg/L'),
        ),
    ]
