# Generated by Django 2.1.5 on 2019-02-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20190206_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='var1_siccite',
            field=models.CharField(default='NULL', max_length=60, verbose_name='m1(g):masse de la coupelle pleine avant séchage à 105°C'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='var2_siccite',
            field=models.CharField(default='NULL', max_length=60, verbose_name='m2(g):masse de la coupelle après séchage à 105°C'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='var3_siccite',
            field=models.CharField(default='NULL', max_length=60, verbose_name='masse de matière sèche en g'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='var4_siccite',
            field=models.CharField(default='NULL', max_length=60, verbose_name='masse de la coupelle vide'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='var5_siccite',
            field=models.CharField(default='NULL', max_length=60, verbose_name='V en L'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='var6_siccite',
            field=models.CharField(default='NULL', max_length=60, verbose_name='[MS] en g/L'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='var7_siccite',
            field=models.CharField(default='NULL', max_length=60, verbose_name='MS en %'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='var8_siccite',
            field=models.CharField(default='NULL', max_length=60, verbose_name="taux d'eau %"),
        ),
    ]
