# Generated by Django 2.1.5 on 2019-02-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20190206_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='var2_mvs',
            field=models.CharField(default='NULL', max_length=200, verbose_name='mb(g):masse du creuset contenant échantillon de boue avant séchage à 105°C'),
        ),
    ]
