# Generated by Django 2.1.5 on 2019-02-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_parametre_interne_analyse_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='var12_dbo_avec_dilution',
            field=models.CharField(default='NULL', max_length=60, verbose_name='Vt/Ve'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_chlorophylle_scor_unesco',
            field=models.CharField(default='NULL', max_length=60, verbose_name="volume solvant initial utilisé pour l'extraction mL"),
        ),
    ]
