# Generated by Django 2.1.5 on 2019-02-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20190206_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='var10_chlorophylle_lorenzen',
            field=models.CharField(max_length=60, verbose_name='Ca en µg/L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var10_chlorophylle_scor_unesco',
            field=models.CharField(max_length=60, verbose_name='Ca en µg/L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var10_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='Ve'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var10_dbo_sans_dilution',
            field=models.CharField(max_length=60, verbose_name='controle'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var11_chlorophylle_lorenzen',
            field=models.CharField(max_length=60, verbose_name='Pa µg/L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var11_chlorophylle_scor_unesco',
            field=models.CharField(max_length=60, verbose_name='Pa µg/L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var11_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='Vt-Ve'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var12_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='Vt/Ve'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var13_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='(Vt-Ve)Vt'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var14_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='DBO'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var15_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='C1/3 <(C1-C2)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var16_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='(C1-C2)<2*C1/3'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var17_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='Controle'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_chlorophylle_lorenzen',
            field=models.CharField(max_length=60, verbose_name='volume prélevé (L)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_chlorophylle_scor_unesco',
            field=models.CharField(max_length=60, verbose_name="volume solvant initial utilisé pour l'extraction mL"),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='C3'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_dbo_sans_dilution',
            field=models.CharField(max_length=60, verbose_name='mesure1 [O2]t0'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_dco',
            field=models.CharField(max_length=60, verbose_name='V2 (mL)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_mest',
            field=models.CharField(max_length=60, verbose_name='P1 (mg)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_mvs',
            field=models.CharField(max_length=200, verbose_name='ma(g):masse du creuset vide'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_ntk',
            field=models.CharField(max_length=60, verbose_name='C (mol/L) titre HCL'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_oxygene_dissous',
            field=models.CharField(max_length=60, verbose_name='v1(mL) volume échantillon titré'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_residu_sec',
            field=models.CharField(max_length=60, verbose_name='mo(mg):masse de la coupelle vide'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_sabm',
            field=models.CharField(max_length=60, verbose_name='Absorbance'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_siccite',
            field=models.CharField(max_length=60, verbose_name='m1(g):masse de la coupelle pleine avant séchage à 105°C'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_silicate',
            field=models.CharField(max_length=60, verbose_name='absorbance'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_silice',
            field=models.CharField(max_length=60, verbose_name='absorbance'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var1_silice_ifremer',
            field=models.CharField(max_length=60, verbose_name='absorbance'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_chlorophylle_lorenzen',
            field=models.CharField(max_length=60, verbose_name='blc 665'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_chlorophylle_scor_unesco',
            field=models.CharField(max_length=60, verbose_name="volume d'eau filtrée L"),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='C4'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_dbo_sans_dilution',
            field=models.CharField(max_length=60, verbose_name='mesure1 [O2]t5'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_dco',
            field=models.CharField(max_length=60, verbose_name='Volume analysé'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_mest',
            field=models.CharField(max_length=60, verbose_name='V (ml)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_mvs',
            field=models.CharField(max_length=200, verbose_name='mb(g):masse du creuset contenant échantillon de boue avant séchage à 105°C'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_ntk',
            field=models.CharField(max_length=60, verbose_name='V0 (ml)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_oxygene_dissous',
            field=models.CharField(max_length=60, verbose_name='v2 (mL) volume thiosulfate versé'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_residu_sec',
            field=models.CharField(max_length=60, verbose_name='m1(mg):masse de la coupelle pleine après séchage à 105°C'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_sabm',
            field=models.CharField(max_length=60, verbose_name='épaisseur de la cuve(1 ou 5cm)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_siccite',
            field=models.CharField(max_length=60, verbose_name='m2(g):masse de la coupelle après séchage à 105°C'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_silicate',
            field=models.CharField(max_length=60, verbose_name='facteur de dilution'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_silice',
            field=models.CharField(max_length=60, verbose_name='facteur de dilution'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var2_silice_ifremer',
            field=models.CharField(max_length=60, verbose_name='facteur de dilution'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_chlorophylle_lorenzen',
            field=models.CharField(max_length=60, verbose_name='blc 750'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_chlorophylle_scor_unesco',
            field=models.CharField(max_length=60, verbose_name='parcours optique en centimètre'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='C1'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_dbo_sans_dilution',
            field=models.CharField(max_length=60, verbose_name='valeur DBO1 mg/L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_dco',
            field=models.CharField(max_length=60, verbose_name='facteur de dilution'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_mest',
            field=models.CharField(max_length=60, verbose_name='P2 (mg)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_mvs',
            field=models.CharField(max_length=60, verbose_name='mc(g):masse du creuset contenant la matière sèche après séchage à 105°C'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_ntk',
            field=models.CharField(max_length=60, verbose_name='V1 (ml)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_oxygene_dissous',
            field=models.CharField(max_length=60, verbose_name='v0 (mL) volume échantillon prélevé'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_residu_sec',
            field=models.CharField(max_length=60, verbose_name='m2(mg) masse de la coupelle après séchage à 180°C'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_sabm',
            field=models.CharField(max_length=60, verbose_name='facteur de dilution'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_siccite',
            field=models.CharField(max_length=60, verbose_name='masse de matière sèche en g'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_silicate',
            field=models.CharField(max_length=60, verbose_name='concentration en mg/L SIO2'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_silice',
            field=models.CharField(max_length=60, verbose_name='concentration en SiO2 µmol'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var3_silice_ifremer',
            field=models.CharField(max_length=60, verbose_name='concentration en SiO2 µmol/L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var4_chlorophylle_lorenzen',
            field=models.CharField(max_length=60, verbose_name='A0 na 665 '),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var4_chlorophylle_scor_unesco',
            field=models.CharField(max_length=60, verbose_name='A0 750'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var4_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='C2'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var4_dbo_sans_dilution',
            field=models.CharField(max_length=60, verbose_name='mesure2 [O2]t0'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var4_dco',
            field=models.CharField(max_length=60, verbose_name='DCO en mg/L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var4_mest',
            field=models.CharField(max_length=60, verbose_name='teneur de MES en mg/L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var4_mvs',
            field=models.CharField(max_length=60, verbose_name='m2(g):masse du creuset contenant la matière calcinée à 550°C'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var4_ntk',
            field=models.CharField(max_length=60, verbose_name='V2 (ml)'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var4_oxygene_dissous',
            field=models.CharField(max_length=60, verbose_name='résultat en mg/L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var4_residu_sec',
            field=models.CharField(max_length=60, verbose_name="V volume de la prise d'essai en mL"),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var4_sabm',
            field=models.CharField(max_length=60, verbose_name='concentration en lauryl sulfate de sodium en mg/L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var4_siccite',
            field=models.CharField(max_length=60, verbose_name='masse de la coupelle vide'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var5_chlorophylle_lorenzen',
            field=models.CharField(max_length=60, verbose_name='A0 na 750'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var5_chlorophylle_scor_unesco',
            field=models.CharField(max_length=60, verbose_name='A0 663'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var5_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='C1/3'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var5_dbo_sans_dilution',
            field=models.CharField(max_length=60, verbose_name='mesure2 [O2]t5'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var5_dco',
            field=models.CharField(max_length=60, verbose_name='poste'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var5_mvs',
            field=models.CharField(max_length=60, verbose_name='V en L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var5_ntk',
            field=models.CharField(max_length=60, verbose_name='facteur de dilution'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var5_residu_sec',
            field=models.CharField(max_length=60, verbose_name='RS en mg/L à 105°C'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var5_siccite',
            field=models.CharField(max_length=60, verbose_name='V en L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var6_chlorophylle_lorenzen',
            field=models.CharField(max_length=60, verbose_name='A0 a 665'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var6_chlorophylle_scor_unesco',
            field=models.CharField(max_length=60, verbose_name='A0 645'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var6_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='C1-C2'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var6_dbo_sans_dilution',
            field=models.CharField(max_length=60, verbose_name='valeur DBO2 mg/L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var6_mvs',
            field=models.CharField(max_length=60, verbose_name='MS en % à 105°C'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var6_ntk',
            field=models.CharField(max_length=60, verbose_name='NTK mg/L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var6_residu_sec',
            field=models.CharField(max_length=60, verbose_name='RS en mg/L à 180°C'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var6_siccite',
            field=models.CharField(max_length=60, verbose_name='[MS] en g/L'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var7_chlorophylle_lorenzen',
            field=models.CharField(max_length=60, verbose_name='A0 a 750'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var7_chlorophylle_scor_unesco',
            field=models.CharField(max_length=60, verbose_name='A0 630'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var7_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='2C1/3'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var7_dbo_sans_dilution',
            field=models.CharField(max_length=60, verbose_name='r expérimentale'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var7_mvs',
            field=models.CharField(max_length=60, verbose_name='[MS] en g/L à 105°C'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var7_siccite',
            field=models.CharField(max_length=60, verbose_name='MS en %'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var8_chlorophylle_lorenzen',
            field=models.CharField(max_length=60, verbose_name='A na 665'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var8_chlorophylle_scor_unesco',
            field=models.CharField(max_length=60, verbose_name='A0 430'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var8_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='C3-C4'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var8_dbo_sans_dilution',
            field=models.CharField(max_length=60, verbose_name='r théorique'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var8_mvs',
            field=models.CharField(max_length=60, verbose_name='MVS en % à 550 °C'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var8_siccite',
            field=models.CharField(max_length=60, verbose_name="taux d'eau %"),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var9_chlorophylle_lorenzen',
            field=models.CharField(max_length=60, verbose_name='A a 665'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var9_chlorophylle_scor_unesco',
            field=models.CharField(max_length=60, verbose_name='A0 410'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var9_dbo_avec_dilution',
            field=models.CharField(max_length=60, verbose_name='Vt'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var9_dbo_sans_dilution',
            field=models.CharField(max_length=60, verbose_name='limite de controle'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='var9_mvs',
            field=models.CharField(max_length=60, verbose_name='[MVS] en g/L à 550°C'),
        ),
        migrations.AlterField(
            model_name='parametre_interne_analyse',
            name='valeur',
            field=models.CharField(max_length=100),
        ),
    ]
