# Generated by Django 2.1.5 on 2019-02-07 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20190207_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var5_ntk',
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='date_etalonnage',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'étalonnage"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='longueur_onde',
            field=models.CharField(default='NULL', max_length=100, verbose_name="longueur d'onde d'analyse"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_chlorophylle_lorenzen',
            field=models.CharField(default='NULL', max_length=100, verbose_name="Lot d'acide chlorydrique utilisé"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_chlorophylle_scor_unesco',
            field=models.CharField(default='NULL', max_length=100, verbose_name="Lot d'acétone utilisé"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_dbo_avec_dilution',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="date de préparation de l'eau de dilution"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_dbo_sans_dilution',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de préparation de la solution de lavage'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_oxygene_dissous',
            field=models.CharField(default='NULL', max_length=100, verbose_name="Volume thiosulfate versé pour l'étalonnage"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var2_chlorophylle_lorenzen',
            field=models.CharField(default='NULL', max_length=100, verbose_name="Lot d'acétone utilisé"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var2_dbo_avec_dilution',
            field=models.CharField(default='NULL', max_length=100, verbose_name="N° échant utilisé pour l'eau de dilution ensemencée"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var2_oxygene_dissous',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Concentration du thiosulfate de sodium'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var3_chlorophylle_lorenzen',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date de préparation de l'HCI"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var3_dbo_avec_dilution',
            field=models.CharField(default='NULL', max_length=100, verbose_name='DCO de cette échantillon'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='visa',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Visa'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var1_ntk',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de préparation du mélange catalyseur'),
        ),
        migrations.AlterField(
            model_name='feuille_calcul',
            name='var4_mest',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date de préparation de la solution de cellulose microcristalline'),
        ),
    ]
