# Generated by Django 2.1.5 on 2019-02-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20190207_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='date_etalonnage',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='longueur_onde',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var1_chlorophylle_lorenzen',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var1_chlorophylle_scor_unesco',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var1_dbo_avec_dilution',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var1_dbo_sans_dilution',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var1_mest',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var1_ntk',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var1_oxygene_dissous',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var2_chlorophylle_lorenzen',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var2_dbo_avec_dilution',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var2_mest',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var2_ntk',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var2_oxygene_dissous',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var3_chlorophylle_lorenzen',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var3_dbo_avec_dilution',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var3_mest',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var3_ntk',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var4_mest',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='var4_ntk',
        ),
        migrations.RemoveField(
            model_name='feuille_calcul',
            name='visa',
        ),
    ]
