# Generated by Django 2.1.5 on 2019-02-07 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20190207_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_mest',
            field=models.CharField(default='NULL', max_length=100, verbose_name='numéro de lot des filtres'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_ntk',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de préparation du mélange catalyseur'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var2_mest',
            field=models.CharField(default='NULL', max_length=100, verbose_name='MEST de la solution de cellulose microcristalline(mg/L)'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var2_ntk',
            field=models.CharField(default='NULL', max_length=100, verbose_name='N° de lot H2SO4'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var3_mest',
            field=models.CharField(default='NULL', max_length=100, verbose_name='rendement(%)'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var4_mest',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date de préparation de la solution de cellulose microcristalline'),
        ),
    ]
