# Generated by Django 2.1.5 on 2019-02-07 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20190207_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_chlorophylle_lorenzen',
            field=models.CharField(default='NULL', max_length=100, verbose_name="Lot d'acide chlorydrique utilisé"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_chlorophylle_scor_unesco',
            field=models.CharField(default='NULL', max_length=100, verbose_name="Lot d'acétone utilisé"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_oxygene_dissous',
            field=models.CharField(default='NULL', max_length=100, verbose_name="Volume thiosulfate versé pour l'étalonnage"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var2_chlorophylle_lorenzen',
            field=models.CharField(default='NULL', max_length=100, verbose_name="Lot d'acétone utilisé"),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var2_oxygene_dissous',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Concentration du thiosulfate de sodium'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var3_chlorophylle_lorenzen',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date de préparation de l'HCI"),
        ),
    ]
