# Generated by Django 2.1.5 on 2019-02-07 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20190207_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuille_calcul',
            name='var1_dco',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date de minéralisation'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var2_dco',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date de titration'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var3_dco',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Lot de la solution ferroïne'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var4_dco',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Lot du H2SO4 4 mol/l'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var5_dco',
            field=models.CharField(default='NULL', max_length=100, verbose_name='volume de sulfate versé pour la détermintation de sa concentration'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var6_dco',
            field=models.CharField(default='NULL', max_length=100, verbose_name='valeur de solution de référence C'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var7_dco',
            field=models.CharField(default='NULL', max_length=100, verbose_name='essaie à blanc V1'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var8_dco',
            field=models.CharField(default='NULL', max_length=100, verbose_name='lot de sulfate de mercure'),
        ),
        migrations.AddField(
            model_name='feuille_calcul',
            name='var9_dco',
            field=models.CharField(default='NULL', max_length=100, verbose_name="lot de sulfate d'argent"),
        ),
    ]
