# Generated by Django 2.1.5 on 2019-02-08 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20190207_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuille_calcul',
            name='heure_mise_sous_essai',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
