# Generated by Django 2.1.5 on 2019-02-14 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_feuille_calcul_var10_dco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuille_calcul',
            name='date_analyse',
            field=models.DateField(default=datetime.datetime(1980, 1, 1, 1, 1, 1)),
        ),
    ]
