# Generated by Django 2.1.5 on 2019-02-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_feuille_calcul_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etalonnage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_lauryl', models.CharField(default='NULL', max_length=100, verbose_name='concentration mg/L de lauryl sulfate de sodium')),
                ('c_mg', models.CharField(default='NULL', max_length=100, verbose_name='concentration mg/L')),
                ('c_micromol_l', models.CharField(default='NULL', max_length=100, verbose_name='concentration µmol/L')),
                ('absorbance', models.CharField(default='NULL', max_length=100, verbose_name='absorbance')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Profil')),
                ('type_analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Type_analyse')),
            ],
        ),
        migrations.CreateModel(
            name='Parametre_etalonnage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('valeur', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='type_analyse',
            name='parametre_etalonnage',
            field=models.ManyToManyField(blank=True, to='myapp.Parametre_etalonnage'),
        ),
    ]
