# Generated by Django 2.1.5 on 2019-02-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_auto_20190218_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuille_calcul',
            name='etalonnage',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Visa'),
        ),
    ]
