# Generated by Django 2.1.5 on 2019-02-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_feuille_calcul_etalonnage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuille_calcul',
            name='etalonnage',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Etalonnage'),
        ),
    ]
