# Generated by Django 2.1.5 on 2019-03-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_auto_20190308_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='nEchantillon',
            field=models.CharField(max_length=60, verbose_name="N° d'échantillon"),
        ),
    ]
